diease_prediction-webapp/diabDiease/urls.py
from django.urls import path
from . import views

app_name = "diabDiease"


urlpatterns = [
    path('',views.home),
    path('predict_diab/',views.predict_diab),
    path('predict_diab/predict/',views.diabetes,name='submit_prediction'),
    path('predict_diab/results_diab/', views.view_diab),

]

diease_prediction-webapp/hrtDIease/urls.py
from django.urls import path
from . import views

app_name = "hrtDIease"


urlpatterns = [
    path('predict_hrt/',views.predict_hrt),
    path('predict_hrt/predict/',views.heart,name='submit_prediction_heart'),
    path('predict_hrt/results_hrt/', views.view_hrt)

]

diease_prediction-webapp/lungDiease/urls.py
from django.urls import path
from . import views

app_name = "lungDiease"


urlpatterns = [
    path('predict_lung/',views.predict_lung),
    path('predict_lung/predict/',views.lung,name='submit_prediction_lung'),
    path('predict_lung/results_lung/', views.view_lung)

]

diease_prediction-webapp/majorpro_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diabDiease.urls', namespace='diabDiease')),
    path('', include('hrtDIease.urls', namespace='hrtDIease')),
    path('', include('brstDiease.urls', namespace='brstDiease')),
    path('', include('kdnDiease.urls', namespace='kdnDiease')),
    path('', include('lungDiease.urls', namespace='lungDiease')),
]

diease_prediction-webapp/templates/diabetes.html
<!DOCTYPE html>{% load static %}

<html lang="en">

<head>
    <title>Diabetes Diease</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    <script type="application/x-javascript">
        addEventListener("load", function() {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="{%  static  'css/style2.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/style.css'  %}" rel="stylesheet" />


    <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">

    <link href="{%  static  'css/bootstrap.min.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/now-ui-kit.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/medium-editor.min.css'  %}" rel="stylesheet" />

    <style>
        body {
            background-image: url("{% static 'images/2.jpg' %}")
        }
    </style>
</head>

<body>


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5>Prediction Input:</h5>
                    <div>Pregnencies : <span id="val1"></span></div>
                    <div>Glucose : <span id="val2"></span></div>
                    <div>Blood Pressure : <span id="val3"></span></div>
                    <div>Skin Thickness : <span id="val4"></span></div>
                    <div>Insulin : <span id="val5"></span></div>
                    <div>BMI : <span id="val6"></span></div>
                    <div>Diabetes Pedigree function : <span id="val7"></span></div>
                    <div>Age : <span id="val8"></span></div>

                    <h5 class="pt-3">Result :</h5>
                    <div id="prediction"></div>
                    <h5 class="pt-3">Accuracy is :</h5>
                    <div id="Accuracy"></div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a class="btn btn-primary" href="/predict_diab/results_diab/" role="button">View DB</a>
                </div>
            </div>
        </div>
    </div>

    <!--background-->

    <h1>Predict Diabetes</h1>
    <div class="bg-agile ">
        <div class="book-appointment ">
            <h2>Medical Information</h2>


            <form action="" id="post-form">
                {% csrf_token %}
                <div class="left-agileits-w3layouts same ">
                    <div class="gaps ">
                        <p>Pregnencies</p>
                        <input type="text " name="preg" placeholder=" " id="Pregnencies">
                    </div>

                    <div class="gaps ">
                        <p>Glucose</p>
                        <input type="text " name="glu" placeholder=" " id="Glucose">
                    </div>

                    <div class="gaps ">
                        <p>Blood Pressure</p>
                        <input type="text " name="bp" placeholder=" " id="Blood_Pressure">
                    </div>

                    <div class="gaps ">
                        <p>Skin Thickness</p>
                        <input type="text " name="st" placeholder=" " id="Skin_Thickness">
                    </div>

                </div>





                <div class="right-agileinfo same ">

                    <div class="gaps ">
                        <p>Insulin</p>
                        <input type="text " name="ins" placeholder=" " id="Insulin">
                    </div>

                    <div class="gaps ">
                        <p>Body Mass Index</p>
                        <input type="text " name="bmi" placeholder=" " id="BMI">
                    </div>
                    <div class="gaps ">
                        <p>Diabetes Pedigree function</p>
                        <input type="text " name="dpf" placeholder=" " id="DPF">
                    </div>
                    <div class="gaps ">
                        <p>Age</p>
                        <input type="text " name="age" placeholder=" " id="Age">
                    </div>
                </div>

                <div class="clear "></div>

                <br><br>
                <!-- <input type="submit" class="btn btn-primary"> -->
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>

            </form>
        </div>



        <!--//copyright-->

        <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
        <!-- Calendar -->
        <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
        <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
        <link rel="stylesheet " href="{%  static  'css/jquery-ui.css'  %}" />
        <script src="{%  static  'js/jquery-ui.js' %} "></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



        <script>
            $(document).on('submit', '#post-form', function(e) {
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: '{% url "diabDiease:submit_prediction" %}',
                    data: {
                        Pregnencies: $('#Pregnencies').val(),
                        Glucose: $('#Glucose').val(),
                        Blood_Pressure: $('#Blood_Pressure').val(),
                        Skin_Thickness: $('#Skin_Thickness').val(),
                        Insulin: $('#Insulin').val(),
                        BMI: $('#BMI').val(),
                        DPF: $('#DPF').val(),
                        Age: $('#Age').val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                        action: 'post'
                    },
                    success: function(json) {
                        document.forms["post-form"].reset();
                        document.getElementById("prediction").innerHTML = json['result']
                        document.getElementById("Accuracy").innerHTML = json['accuracy']
                        document.getElementById("val1").innerHTML = json['Pregnencies']
                        document.getElementById("val2").innerHTML = json['Glucose']
                        document.getElementById("val3").innerHTML = json['Blood_Pressure']
                        document.getElementById("val4").innerHTML = json['Skin_Thickness']
                        document.getElementById("val5").innerHTML = json['Insulin']
                        document.getElementById("val6").innerHTML = json['BMI']
                        document.getElementById("val7").innerHTML = json['DPF']
                        document.getElementById("val8").innerHTML = json['Age']
                    },
                    error: function(xhr, errmsg, err) {

                    }
                });
            })
        </script>

</body>

</html>

diease_prediction-webapp/templates/heart.html
<!DOCTYPE html>{% load static %}

<html>

<head>
    <title>Heart Diease</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="application/x-javascript">
        addEventListener("load", function() {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <link href="{%  static  'css/style2.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/style.css'  %}" rel="stylesheet" />


    <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">

    <link href="{%  static  'css/bootstrap.min.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/now-ui-kit.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/medium-editor.min.css'  %}" rel="stylesheet" />


    <style>
        body {
            background-image: url("{% static 'images/3.jpg' %}")
        }
    </style>

</head>

<body>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5>Prediction Input:</h5>
                    <div>Age : <span id="val1"></span></div>
                    <div>Sex : <span id="val2"></span></div>
                    <div>chest pain : <span id="val3"></span></div>
                    <div>trestbps : <span id="val4"></span></div>
                    <div>chol : <span id="val5"></span></div>
                    <div>fbs : <span id="val6"></span></div>
                    <div> restecg : <span id="val7"></span></div>
                    <div>thalach : <span id="val8"></span></div>
                    <div>exang : <span id="val9"></span></div>
                    <div>oldpeak : <span id="val10"></span></div>
                    <div>slope : <span id="val11"></span></div>
                    <div>ca : <span id="val12"></span></div>
                    <div>thal : <span id="val13"></span></div>

                    <h5 class="pt-3">Result :</h5>
                    <div id="prediction"></div>
                    <h5 class="pt-3">Accuracy is :</h5>
                    <div id="Accuracy"></div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a class="btn btn-primary" href="/predict_hrt/results_hrt/" role="button">View DB</a>
                </div>
            </div>
        </div>
    </div>

    <!--background-->
    <!--background-->
    
    <h1>Predict Heart disease</h1>
    <div class="bg-agile ">
        <div class="book-appointment ">
            <h2>Medical Information</h2>

            <form action="" id="post-form">
                {% csrf_token %}
                <div class="left-agileits-w3layouts same ">
                    <div class="gaps ">
                        <p>Age</p>
                        <input type="text " name="age" placeholder=" " id="Age" />
                    </div>

                    <div class="gaps ">
                        <p>Gender</p>
                        <input type="text " name="sex" placeholder=" " id="Sex" />
                    </div>

                    <div class="gaps ">
                        <p>Chest Pain(cp)</p>
                        <input type="text " name="cp" placeholder=" " id="chest_pain" />
                    </div>

                    <div class="gaps ">
                        <p>trestbps</p>
                        <input type="text " name="trestbps" placeholder=" " id="trestbps" />
                    </div>
                    <div class="gaps ">
                        <p>cholestrol</p>
                        <input type="text " name="chol" placeholder=" " id="chol" />
                    </div>
                    <div class="gaps ">
                        <p>fbs</p>
                        <input type="text " name="fbs" placeholder=" " id="fbs" />
                    </div>
                </div>

                <div class="right-agileinfo same ">

                    <div class="gaps ">
                        <p>Restecg</p>
                        <input type="text " name="restecg" placeholder=" " id="restecg" />
                    </div>
                    <div class="gaps ">
                        <p>thalach</p>
                        <input type="text " name="thalach" placeholder=" " id="thalach" />
                    </div>

                    <div class="gaps ">
                        <p>exang</p>
                        <input type="text " name="exang" placeholder=" " id="exang" />
                    </div>

                    <div class="gaps ">
                        <p>oldpeak</p>
                        <input type="text " name="oldpeak" placeholder=" " id="oldpeak" />
                    </div>
                    <div class="gaps ">
                        <p>slope</p>
                        <input type="text " name="slope" placeholder=" " id="slope" />
                    </div>
                    <div class="gaps ">
                        <p>ca</p>
                        <input type="text " name="ca" placeholder=" " id="ca" />
                    </div>
                    <div class="gaps ">
                        <p>thal</p>
                        <input type="text " name="thal" placeholder=" " id="thal" />
                    </div>
                </div>

                <div class="clear "></div>
                <br>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>

            </form>
        </div>


    </div>
    <!--copyright-->

    <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
    <!-- Calendar -->
    <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
    <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
    <link rel="stylesheet " href="{%  static  'css/jquery-ui.css'  %}" />
    <script src="{%  static  'js/jquery-ui.js' %} "></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <script>
        $(document).on('submit', '#post-form', function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "hrtDIease:submit_prediction_heart" %}',
                data: {
                    Age: $('#Age').val(),
                    Sex: $('#Sex').val(),
                    chest_pain: $('#chest_pain').val(),
                    trestbps: $('#trestbps').val(),
                    chol: $('#chol').val(),
                    fbs: $('#fbs').val(),
                    restecg: $('#restecg').val(),
                    thalach: $('#thalach').val(),
                    exang: $('#exang').val(),
                    oldpeak: $('#oldpeak').val(),
                    slope: $('#slope').val(),
                    ca: $('#ca').val(),
                    thal: $('#thal').val(),


                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function(json) {
                    document.forms["post-form"].reset();
                    document.getElementById("prediction").innerHTML = json['result']
                    document.getElementById("Accuracy").innerHTML = json['accuracy']
                    document.getElementById("val1").innerHTML = json['Age']
                    document.getElementById("val2").innerHTML = json['Sex']
                    document.getElementById("val3").innerHTML = json['chest_pain']
                    document.getElementById("val4").innerHTML = json['trestbps']
                    document.getElementById("val5").innerHTML = json['chol']
                    document.getElementById("val6").innerHTML = json['fbs']
                    document.getElementById("val7").innerHTML = json['restecg']
                    document.getElementById("val8").innerHTML = json['thalach']
                    document.getElementById("val9").innerHTML = json['exang']
                    document.getElementById("val10").innerHTML = json['oldpeak']
                    document.getElementById("val11").innerHTML = json['slope']
                    document.getElementById("val12").innerHTML = json['ca']
                    document.getElementById("val13").innerHTML = json['thal']
                },
                error: function(xhr, errmsg, err) {

                }
            });
        })
    </script>
</body>

</html>

diease_prediction-webapp/templates/home.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Diease predictor</title>

    <style type=text/css>
        div {
            color: white;
        }
        
        h1 {
            color: 'white';
            font-family: arial, sans-serif;
            font-size: 55px;
            font-weight: bold;
            margin-top: 200px;
        }
        
        h2 {
            color: 'white';
            font-family: arial, sans-serif;
            font-size: 20px;
            font-weight: bold;
            margin-top: 400px;
        }
        
        body {
            background-image:url("{% static 'images/1.jpg'%}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
        
        input[type=submit] {
            background-color: #693996;
            border: 2px;
            color: white;
            padding: 16px 32px;
            cursor: pointer;
            margin-top: 15px;
            border-radius: 21px;
            width: 25%;
        }
        
        input[type=submit]:hover {
            background-color: #4dc3ff;
            color: rgb(37, 25, 25);
            animation: shake 0.5s forwards 0s linear !important;
        }
        
        @keyframes shake {
            0% {
                transform: rotate(3deg);
            }
            20% {
                transform: rotate(-3deg);
            }
            40% {
                transform: rotate(3deg);
            }
            60% {
                transform: rotate(-3deg);
            }
            80% {
                transform: rotate(3deg);
            }
            100% {
                transform: rotate(0deg);
            }
        }
    </style>
</head>

<body>
    <div align="center">
        <h1>Welcome to Diease predictor</h1>


        <form action="predict_diab">
            <input type="submit" value="Let's predict Diabetes">
        </form>
        <form action="predict_hrt">
            <input type="submit" value="Let's predict Heart Diease">
        </form>
        <form action="predict_breast">
            <input type="submit" value="Let's predict Breast Cancer">
        </form>
        <form action="predict_kdn">
            <input type="submit" value="Let's predict Kiney Diease">
        </form>
        <form action="predict_lung">
            <input type="submit" value="Let's predict Lung cancer">
        </form>
    </div>


</body>

</html>

diease_prediction-webapp/templates/lung.html
<!DOCTYPE html>{% load static %}

<html>

<head>
    <title>Lung Cancer</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="application/x-javascript">
        addEventListener("load", function() {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="{%  static  'css/style2.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/style.css'  %}" rel="stylesheet" />

    <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" />
    <link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" />

    <link href="{%  static  'css/bootstrap.min.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/now-ui-kit.css'  %}" rel="stylesheet" />
    <link href="{%  static  'css/medium-editor.min.css'  %}" rel="stylesheet" />

    <style>
        body {
            background-image: url("{% static 'images/3.jpg' %}");
        }
        
        .btn_middle {
            margin: auto;
        }
    </style>
    ">
    <!--//fonts-->
</head>

<body>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5>Prediction Input:</h5>
                    <div>Age : <span id="val1"></span></div>
                    <div>Smokes : <span id="val2"></span></div>
                    <div>AreaQ : <span id="val3"></span></div>
                    <div>Alkohol : <span id="val4"></span></div>

                    <h5 class="pt-3">Result :</h5>
                    <div id="prediction"></div>
                    <h5 class="pt-3">Accuracy is :</h5>
                    <div id="Accuracy"></div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a class="btn btn-primary" href="/predict_lung/results_lung/" role="button">View DB</a>
                </div>
            </div>
        </div>
    </div>

    <!--background-->

    <h1>Predict Lung Cancer</h1>
    <div class="bg-agile">
        <div class="book-appointment">
            <h2>Medical Information</h2>

            <form action="" id="post-form">
                {% csrf_token %}
                <div class="left-agileits-w3layouts same">

                    <div class="gaps">
                        <p>Age</p>
                        <input type="text " id="age" placeholder="" />
                    </div>
                    <div class="gaps">
                        <p>Smoking</p>
                        <input type="text " id="smokes" placeholder="" />
                    </div>


                </div>

                <div class="right-agileinfo same">

                    <div class="gaps">
                        <p>AreaQ</p>
                        <input type="text " id="areaq" placeholder="" />
                    </div>

                    <div class="gaps">
                        <p>Alcohol</p>
                        <input type="text " id="alkohol" placeholder="" />
                    </div>
                </div>

                <div class="clear"></div>


                <br><br>
                <!-- <input type="submit" class="btn btn-primary"> -->
                <button type="submit" value="Submit" class="btn btn-primary btn_middle" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
    <!--copyright-->

    <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
    <!-- Calendar -->
    <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
    <script type="text/javascript " src="{%  static  'js/jquery-2.1.4.min.js'  %}"></script>
    <link rel="stylesheet " href="{%  static  'css/jquery-ui.css'  %}" />
    <script src="{%  static  'js/jquery-ui.js' %} "></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



    <script>
        $(document).on('submit', '#post-form', function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "lungDiease:submit_prediction_lung" %}',
                data: {
                    age: $('#age').val(),
                    smokes: $('#smokes').val(),
                    areaq: $('#areaq').val(),
                    alkohol: $('#alkohol').val(),

                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function(json) {
                    document.forms["post-form"].reset();
                    document.getElementById("prediction").innerHTML = json['result']
                    document.getElementById("Accuracy").innerHTML = json['accuracy']
                    document.getElementById("val1").innerHTML = json['Age']
                    document.getElementById("val2").innerHTML = json['Smokes']
                    document.getElementById("val3").innerHTML = json['AreaQ']
                    document.getElementById("val4").innerHTML = json['Alkohol']

                },
                error: function(xhr, errmsg, err) {

                }
            });
        })
    </script>

</body>

</html>